<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Report Top Up</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }

        h1 {
            text-align: center;
        }

        table {
            border-collapse: collapse;
            width: 100%;
            margin-top: 20px;
        }

        th,
        td {
            border: 1px solid #444;
            padding: 8px;
            vertical-align: middle;
        }

        th {
            background-color: #eee;
            text-align: left;
        }

        th.align-right,
        td.align-right {
            text-align: right;
        }

        .badge {
            display: inline-block;
            padding: 3px 7px;
            border-radius: 4px;
            font-size: 11px;
            color: white;
        }

        .badge-default {
            background-color: #4caf50;
            /* green */
        }

        .badge-destructive {
            background-color: #f44336;
            /* red */
        }

        .filters {
            margin-bottom: 10px;
        }

        .filters span {
            display: inline-block;
            margin-right: 20px;
            font-weight: bold;
        }

        footer {
            position: fixed;
            bottom: 10px;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>

<body>
    <h1>Report Top Up</h1>
    <div class="filters">
        <span>Start Date: {{ $filters['start_date'] ?? '-' }}</span>
        <span>End Date: {{ $filters['end_date'] ?? '-' }}</span>
        <span>Generated: {{ \Carbon\Carbon::now()->format('Y-m-d H:i:s') }}</span>
    </div>
    <table>
        <thead>
            <tr>
                <th>Kode Transaksi</th>
                <th>Barcode</th>
                <th>Nama Karyawan</th>
                <th>Toko</th>
                <th>Divisi</th>
                <th>Waktu Transaksi</th>
                <th>Top Up By</th>
                <th class="align-right">Nominal</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($topUps as $topUp)
                <tr>
                    <td>{{ $topUp->code }}</td>
                    <td>{{ $topUp->memberCard->card_number ?? '-' }}</td>
                    <td>{{ $topUp->memberCard->user->name ?? '-' }}</td>
                    <td>{{ $topUp->memberCard->user->store->name ?? '-' }}</td>
                    <td>{{ $topUp->memberCard->user->division->name ?? '-' }}</td>
                    <td>{{ $topUp->created_at->format('Y-m-d H:i:s') }}</td>
                    <td>{{ $topUp->topUpBy->name ?? '-' }}</td>
                    <td class="align-right">{{ number_format($topUp->amount, 0, ',', '.') }}</td>
                    <td>
                        @php
                            $status = $topUp->status;
                             $statusLabels = [
                                'success' => 'Success',
                                'canceled' => 'Cancel',
                            ];
                            $badgeClass = $status === 'success' ? 'badge-default' : 'badge-destructive';
                            $statusLabel = $statusLabels[$status] ?? ucfirst($status);
                        @endphp
                        <span class="badge {{ $badgeClass }}">{{ $statusLabel }}</span>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" style="text-align:center;">No data available for this period.</td>
                </tr>
            @endforelse
        </tbody>
        <tfoot>
            <tr>
                <th colspan="7" class="align-right">Total Success</th>
                <th class="align-right">{{ number_format($totalSuccess, 0, ',', '.') }}</th>
                <th></th>
            </tr>
            <tr>
                <th colspan="7" class="align-right">Total Cancel</th>
                <th class="align-right">{{ number_format($totalCanceled, 0, ',', '.') }}</th>
                <th></th>
            </tr>
        </tfoot>
    </table>
    <footer>
        &copy; {{ date('Y') }} WAROENG44S - Generated by System
    </footer>
</body>

</html>
